<template>
  <doc-page title="Notification drawer">
    <template #description>A <b>notification drawer</b> is a place where users can view and manage notifications that are generated by the system. It allows them to see a list of notifications without the need to navigate away from the current screen.</template>

    <template #apidocs>
      <component-info name="PfNotificationDrawer" />
      <component-info name="PfNotificationDrawerBody" />
      <component-info name="PfNotificationDrawerGroup" />
      <component-info name="PfNotificationDrawerGroupList" />
      <component-info name="PfNotificationDrawerHeader" />
      <component-info name="PfNotificationDrawerList" />
      <component-info name="PfNotificationDrawerListItem" />
      <component-info name="PfNotificationDrawerListItemBody" />
      <component-info name="PfNotificationDrawerListItemHeader" />
    </template>

    <pre v-md>
      ## Examples
    </pre>

    <story-canvas title="Basic">
      <pf-notification-drawer>
        <pf-notification-drawer-header count="3" @close="() => {}">
          <pf-dropdown position="right">
            <template #toggle>
              <pf-menu-toggle variant="plain" />
            </template>

            <pf-dropdown-item>Action</pf-dropdown-item>
          </pf-dropdown>
        </pf-notification-drawer-header>

        <pf-notification-drawer-body>
          <pf-notification-drawer-list aria-label="Notifications in the basic example">
            <pf-notification-drawer-list-item variant="info">
              <pf-notification-drawer-list-item-header
                variant="info"
                title="Unread info notification title"
                sr-title="Info notification:"
              >
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="5 minutes ago">
                This is an info notification description.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>

            <pf-notification-drawer-list-item variant="danger">
              <pf-notification-drawer-list-item-header
                variant="danger"
                title="Unread danger notification title. This is a long title to show how the title will wrap if it is long and wraps to multiple lines."
                sr-title="Danger notification:"
              >
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="10 minutes ago">
                This is a danger notification description. This is a long description to show how the title will wrap if
                it is long and wraps to multiple lines.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>

            <pf-notification-drawer-list-item variant="danger">
              <pf-notification-drawer-list-item-header
                :truncate-title="1"
                variant="danger"
                title="Unread danger notification title. This is a long title to show how the title will be truncated if it is long and will be shown in a single line."
                sr-title="Danger notification:"
              >
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="10 minutes ago">
                This is a danger notification description. This is a long description to show how the title will wrap if
                it is long and wraps to multiple lines.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>

            <pf-notification-drawer-list-item variant="warning" read>
              <pf-notification-drawer-list-item-header
                variant="warning"
                title="Read warning notification title"
                sr-title="Warning notification:"
              >
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="20 minutes ago">
                This is a warning notification description.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>

            <pf-notification-drawer-list-item variant="success" read>
              <pf-notification-drawer-list-item-header
                variant="success"
                title="Read success notification title"
                sr-title="Success notification:"
              >
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="30 minutes ago">
                This is a success notification description.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>

            <pf-notification-drawer-list-item read>
              <pf-notification-drawer-list-item-header title="Read (default) notification title" sr-title="notification:">
                <pf-dropdown position="right">
                  <template #toggle>
                    <pf-menu-toggle variant="plain" />
                  </template>

                  <pf-dropdown-item>Action</pf-dropdown-item>
                </pf-dropdown>
              </pf-notification-drawer-list-item-header>
              <pf-notification-drawer-list-item-body timestamp="35 minutes ago">
                This is a default notification description.
              </pf-notification-drawer-list-item-body>
            </pf-notification-drawer-list-item>
          </pf-notification-drawer-list>
        </pf-notification-drawer-body>
      </pf-notification-drawer>
    </story-canvas>

    <story-canvas title="Groups">
      <pf-notification-drawer>
        <pf-notification-drawer-header count="4">
          <pf-dropdown position="right">
            <template #toggle>
              <pf-menu-toggle variant="plain" />
            </template>

            <pf-dropdown-item>Action</pf-dropdown-item>
          </pf-dropdown>
        </pf-notification-drawer-header>

        <pf-notification-drawer-body>
          <pf-notification-drawer-group-list>
            <pf-notification-drawer-group
              title="First notification group"
              count="2"
            >
              <pf-notification-drawer-list aria-label="Notifications in the basic example">
                <pf-notification-drawer-list-item variant="info">
                  <pf-notification-drawer-list-item-header
                    variant="info"
                    title="Unread info notification title"
                    sr-title="Info notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="5 minutes ago">
                    This is an info notification description.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="danger">
                  <pf-notification-drawer-list-item-header
                    variant="danger"
                    title="Unread danger notification title. This is a long title to show how the title will wrap if it is long and wraps to multiple lines."
                    sr-title="Danger notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="10 minutes ago">
                    This is a danger notification description. This is a long description to show how the title will wrap if
                    it is long and wraps to multiple lines.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="warning" read>
                  <pf-notification-drawer-list-item-header
                    variant="warning"
                    title="Read warning notification title"
                    sr-title="Warning notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="10 minutes ago">
                    This is a danger notification description. This is a long description to show how the title will wrap if
                    it is long and wraps to multiple lines.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="success" read>
                  <pf-notification-drawer-list-item-header
                    variant="success"
                    title="Read success notification title"
                    sr-title="Success notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="30 minutes ago">
                    This is a success notification description.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>
              </pf-notification-drawer-list>
            </pf-notification-drawer-group>


            <pf-notification-drawer-group
              title="Second notification group"
              count="2"
            >
              <pf-notification-drawer-list aria-label="Notifications in the second group">
                <pf-notification-drawer-list-item variant="info">
                  <pf-notification-drawer-list-item-header
                    variant="info"
                    title="Unread info notification title"
                    sr-title="Info notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="5 minutes ago">
                    This is an info notification description.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="danger">
                  <pf-notification-drawer-list-item-header
                    variant="danger"
                    title="Unread danger notification title. This is a long title to show how the title will wrap if it is long and wraps to multiple lines."
                    sr-title="Danger notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="10 minutes ago">
                    This is a danger notification description. This is a long description to show how the title will wrap
                    if it is long and wraps to multiple lines.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="warning" read>
                  <pf-notification-drawer-list-item-header
                    variant="warning"
                    title="Read warning notification title"
                    sr-title="Warning notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="20 minutes ago">
                    This is a warning notification description.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>

                <pf-notification-drawer-list-item variant="success" read>
                  <pf-notification-drawer-list-item-header
                    variant="success"
                    title="Read success notification title"
                    sr-title="Success notification:"
                  >
                    <pf-dropdown position="right">
                      <template #toggle>
                        <pf-menu-toggle variant="plain" />
                      </template>

                      <pf-dropdown-item>Action</pf-dropdown-item>
                    </pf-dropdown>
                  </pf-notification-drawer-list-item-header>
                  <pf-notification-drawer-list-item-body timestamp="30 minutes ago">
                    This is a success notification description.
                  </pf-notification-drawer-list-item-body>
                </pf-notification-drawer-list-item>
              </pf-notification-drawer-list>
            </pf-notification-drawer-group>

            <pf-notification-drawer-group
              title="Third notification group. This is a long title to show how the title will be truncated if it is long and will be shown in a single line."
              count="0"
              :truncate-title="1"
              read
            >
              <pf-notification-drawer-list aria-label="Notifications in the third group">
                <pf-empty-state variant="full">
                  <pf-empty-state-header heading-level="h2" title="No alerts found">
                    <template #icon>
                      <magnifying-glass-icon />
                    </template>
                  </pf-empty-state-header>
                  <pf-empty-state-body>
                    There are currently no critical alerts firing. There may be firing alerts of other severities or
                    silenced critical alerts however.
                  </pf-empty-state-body>
                  <pf-empty-state-footer>
                    <pf-empty-state-actions>
                      <pf-button variant="link">Action</pf-button>
                    </pf-empty-state-actions>
                  </pf-empty-state-footer>
                </pf-empty-state>
              </pf-notification-drawer-list>
            </pf-notification-drawer-group>

          </pf-notification-drawer-group-list>
        </pf-notification-drawer-body>
      </pf-notification-drawer>
    </story-canvas>
  </doc-page>
</template>

<script lang="ts" setup>
import MagnifyingGlassIcon from '@vue-patternfly/icons/magnifying-glass-icon';
</script>
