name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: npm install --global pnpm
      - run: pnpm install
      - run: pnpm turbo run lint --filter "./packages/*"
      - run: pnpm test
